/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mSuUJgN1a5l
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import * as React from "react";
import { Link } from "gatsby";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { StaticImage } from "gatsby-plugin-image";
import { MountainIcon } from "./MountainIcon";
import Header from "./Header";
import Hero from "./Hero";
import Services from "./Services";
import Products from "./Products";
import Testimonials from "./Testimonials";
import Contact from "./Contact";
import Footer from "./Footer";

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      {/* <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" to="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Your Business Agency</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            to="#services"
          >
            Services
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            to="#products"
          >
            Products
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            to="#testimonials"
          >
            Testimonials
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            to="#contact-us"
          >
            Contact
          </Link>
        </nav>
      </header> */}
      <Header />
      <main className="flex-1">
        {/* <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Transform Your Business
                  </h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    Get started today with our comprehensive suite of services
                    and products.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    to="#"
                  >
                    Get Started
                  </Link>
                </div>
              </div>
              <img
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                height="550"
                src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section> */}
        <Hero />
        {/* <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
          id="services"
        >
          <div className="container px-4 md:px-6 space-y-4">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Our Services
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  We offer a wide range of services to help your business
                  succeed.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 md:gap-12 lg:max-w-none">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Strategy</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  We help you develop a comprehensive business strategy to
                  achieve your goals.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Marketing</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Our marketing experts will help you reach your target audience
                  and drive growth.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Operations</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  We optimize your business operations to improve efficiency and
                  productivity.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Technology</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Our tech experts will help you leverage the latest tools and
                  technologies to drive innovation.
                </p>
              </div>
            </div>
          </div>
        </section> */}
        <Services />
        {/* <section className="w-full py-12 md:py-24 lg:py-32" id="products">
          <div className="container px-4 md:px-6 space-y-4">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Our Products
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Check out our innovative products that can help transform your
                  business.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 md:gap-12 lg:max-w-none">
              <div className="grid gap-1">
                <img
                  alt="Product 1"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="200"
                  src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold">Product 1</h3>
              </div>
              <div className="grid gap-1">
                <img
                  alt="Product 2"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="200"
                  src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold">Product 2</h3>
              </div>
              <div className="grid gap-1">
                <img
                  alt="Product 3"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="200"
                  src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold">Product 3</h3>
              </div>
              <div className="grid gap-1">
                <img
                  alt="Product 4"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center"
                  height="200"
                  src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder.svg"
                  width="300"
                />
                <h3 className="text-lg font-bold">Product 4</h3>
              </div>
            </div>
          </div>
        </section> */}
        <Products />
        {/* <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
          id="testimonials"
        >
          <div className="container px-4 md:px-6 space-y-4">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  What Our Clients Say
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Hear from our satisfied clients about their experience with
                  our services.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 md:gap-12 lg:max-w-none">
              <div className="grid gap-4 bg-white h-full w-full">
                <div className="rounded-md border border-gray-200 p-4 shadow-sm dark:border-gray-800">
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Working with Your Business Agency has been a
                    game-changer&#13; for our company. Their expertise and
                    innovative solutions&#13; have helped us achieve our goals.
                    <br />
                    <br />
                  </p>
                  <div className="mt-4 flex items-center space-x-2">
                    <Avatar>
                      <AvatarImage>
                        <StaticImage
                          src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder-avatar.jpg"
                          alt="Avatar"
                        />
                      </AvatarImage>
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div className="place-items-end">
                      <h4 className="text-sm font-medium">John Doe</h4>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        CEO, Acme Inc.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="grid gap-4 bg-white h-full w-full">
                <div className="rounded-md border border-gray-200 p-4 shadow-sm dark:border-gray-800">
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    I highly recommend Your Business Agency to any company&#13;
                    looking to take their business to the next level. Their&#13;
                    team is knowledgeable, responsive, and truly cares
                    about&#13; our success.
                    <br />
                    <br />
                  </p>
                  <div className="mt-4 flex items-center space-x-2">
                    <Avatar>
                      <AvatarImage>
                        <StaticImage
                          src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder-avatar.jpg"
                          alt="Avatar"
                        />
                      </AvatarImage>
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div className="place-items-end">
                      <h4 className="text-sm font-medium">Jane Doe</h4>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        COO, Globex Inc.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="grid gap-4 bg-white h-full w-full">
                <div className="rounded-md border border-gray-200 p-4 shadow-sm dark:border-gray-800">
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    The team at Your Business Agency has been instrumental
                    in&#13; helping us navigate the challenges of our industry.
                    Their&#13; strategic guidance and innovative solutions have
                    been&#13; invaluable.
                  </p>
                  <div className="mt-4 flex items-center space-x-2">
                    <Avatar>
                      <AvatarImage>
                        <StaticImage
                          src="https://ncbinnovation.blob.core.windows.net/static-cdn/images/placeholder-avatar.jpg"
                          alt="Avatar"
                        />
                      </AvatarImage>
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div className="place-items-end">
                      <h4 className="text-sm font-medium">John Smith</h4>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        CFO, Stark Industries
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section> */}
        <Testimonials />
        {/* <section className="w-full py-12 md:py-24 lg:py-32" id="contact-us">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Get in Touch
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Have a question or want to learn more about our services? Fill
                  out the form below and we'll be in touch.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex flex-col space-y-2">
                  <Input
                    className="max-w-lg flex-1"
                    placeholder="Name"
                    type="text"
                  />
                  <Input
                    className="max-w-lg flex-1"
                    placeholder="Email"
                    type="email"
                  />
                  <Textarea className="max-w-lg flex-1" placeholder="Message" />
                  <button
                    className={
                      "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground shadow hover:bg-primary/90 h-9 px-4 py-2 w-full"
                    }
                    type="submit"
                  >
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </section> */}
        <Contact />
      </main>
      {/* <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Your Business Agency. All rights reserved.
        </p>
      </footer> */}
      <Footer />
    </div>
  );
}
